/* Français Familier — offline service worker (generated by build.py).
   Precaches the whole app, audio included, so it runs with no signal.
   VERSION changes on every build, which retires the old cache. */
const CACHE = 'ff2-3e4ae24ec4';
const FILES = ["./", "./index.html", "./manifest.json", "./icon-192.png", "./icon-512.png", "./apple-touch-icon.png", "./audio-1.js?v=e7e71f2d", "./audio-2.js?v=9004ac04", "./fonts/bricolage.woff2", "./fonts/manrope.woff2"];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(FILES)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== location.origin) return;
  e.respondWith(
    caches.open(CACHE).then((c) =>
      c.match(req, {ignoreSearch: req.mode === 'navigate'}).then((hit) =>
        hit || fetch(req).then((res) => {
          if (res && res.ok) c.put(req, res.clone());
          return res;
        }).catch(() => c.match('./index.html'))
      )
    )
  );
});
